sudo: required
rvm:
  - 2.5.8
before_install:
  - gem install bundler
  - bundle install
  - docker pull petems/centos-7-docker-vagrant-insecure-key
script:
  - bundle exec rake validate
  - bundle exec rake test:unit
  - bundle exec rake test:docker_acceptance
