name: "Datadog CI Visibility"
on:
  pull_request:
  push:
  schedule:
    - cron:  '30 5,17 * * *'
jobs:
  datadog_ci_visibility:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake test:unit
